apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: messaging # specify the namespace here once its created or use default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pod # deployment will use this label to manage pods
  template:
    metadata:
      labels:
        app: kafka-pod # use the same label as above
    spec:
      containers:
        - name: kafka-pod
          image: confluentinc/cp-kafka:7.6.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service.messaging.svc.cluster.local:2181" #also use the serivce zookeeper-service:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service.messaging.svc.cluster.local:9092" #also use the serivce kafka-service:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"