apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
spec:
  containers:
    - name: kafka
      image: confluentinc/cp-kafka:7.6.1
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"