apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-pod
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:7.6.1
      ports:
        - containerPort: 2181
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"